function h = fixfig(ftype)
h = gcf; 
switch ftype
    case 1
        set(h,'units','centimeters',...
            'position',[6 10 8 6],...
            'paperunits','centimeters',...
            'papersize',[8 6])
        ha = gca;
        set(ha, 'fontname','times new roman',...
            'fontsize', 10)
    case 2
        set(h,'units','centimeters',...
            'position',[6 10 12 6.75],...
            'paperunits','centimeters',...
            'papersize',[12 6.75])
        ha = gca;
        set(ha, 'fontname','times new roman',...
            'fontsize', 10)
    otherwise
        error('unknown figure type')
end
